blank_issues_enabled: false
contact_links:
  - name: Salesforce DX Community
    url: https://success.salesforce.com/issues_index?tag=Salesforce%20DX
    about: Please ask and answer questions here.
  - name: Feature request
    url: https://github.com/forcedotcom/salesforcedx-vscode/discussions/new?category=ideas
    about: Feature requests should be opened as discussions
