/*
 * Copyright (c) 2026, salesforce.com, inc.
 * All rights reserved.
 * Licensed under the BSD 3-Clause license.
 * For full license text, see LICENSE.txt file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */

/* Node fs/path: desktop fixture + headless server bootstrap only — not used from browser-driven web spec steps. */

import * as fs from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';

/**
 * Component names required by LWC Playwright specs when bundles are pre-seeded on disk (desktop).
 */
export const LWC_E2E_COMPONENT_NAMES = ['autoComp', 'gtdHtmlComp', 'gtdJsComp', 'indexComp'] as const;

/** Seeded bundle content for `gtdHtmlComp` (desktop pre-seed + web patch after `SFDX: Create Lightning Web Component`). */
export const LWC_GTD_HTML_COMP_SEED_JS = `import { LightningElement } from 'lwc';

export default class Lwc1 extends LightningElement {
    greeting = 'Hello, World!';
}
`;

export const LWC_GTD_HTML_COMP_SEED_HTML = `<template>
    <p>{greeting}</p>
</template>
`;

/** Standard LWC JS content generated by @salesforce/templates (class name is always "Lwc1"). */
const lwcJs = `import { LightningElement } from 'lwc';

export default class Lwc1 extends LightningElement {}
`;

/** Minimal `CustomLabels.labels-meta.xml` seeded into scratch workspaces (optional metadata for LSP). */
export const LWC_E2E_SEED_CUSTOM_LABELS_XML = `<?xml version="1.0" encoding="UTF-8"?>
<CustomLabels xmlns="http://soap.sforce.com/2006/04/metadata">
    <labels>
        <fullName>LwcE2eSeedLabel</fullName>
        <value>Seed value</value>
    </labels>
</CustomLabels>
`;

/** Minimal LWC HTML template. */
const lwcHtml = `<template>
</template>
`;

/** LWC metadata file. */
const lwcXml = `<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>64.0</apiVersion>
    <isExposed>false</isExposed>
</LightningComponentBundle>
`;

/**
 * Create a minimal Salesforce DX project with pre-built LWC bundles for E2E tests.
 * Used by the web headless server and desktop Playwright fixtures.
 */
export const createLwcTestWorkspace = async (): Promise<string> => {
  const workspaceDir = await fs.mkdtemp(path.join(os.tmpdir(), 'vscode-lwc-e2e-'));
  const lwcDir = path.join(workspaceDir, 'force-app', 'main', 'default', 'lwc');

  await fs.writeFile(
    path.join(workspaceDir, 'sfdx-project.json'),
    JSON.stringify(
      {
        packageDirectories: [{ path: 'force-app', default: true }],
        namespace: '',
        sfdcLoginUrl: 'https://login.salesforce.com',
        sourceApiVersion: '64.0',
        defaultLwcLanguage: 'javascript'
      },
      null,
      2
    )
  );

  for (const name of LWC_E2E_COMPONENT_NAMES) {
    const compDir = path.join(lwcDir, name);
    await fs.mkdir(compDir, { recursive: true });
    const js = name === 'gtdHtmlComp' ? LWC_GTD_HTML_COMP_SEED_JS : lwcJs;
    const html = name === 'gtdHtmlComp' ? LWC_GTD_HTML_COMP_SEED_HTML : lwcHtml;
    await Promise.all([
      fs.writeFile(path.join(compDir, `${name}.js`), js),
      fs.writeFile(path.join(compDir, `${name}.html`), html),
      fs.writeFile(path.join(compDir, `${name}.js-meta.xml`), lwcXml)
    ]);
  }

  const labelsDir = path.join(workspaceDir, 'force-app', 'main', 'default', 'labels');
  await fs.mkdir(labelsDir, { recursive: true });
  await fs.writeFile(path.join(labelsDir, 'CustomLabels.labels-meta.xml'), LWC_E2E_SEED_CUSTOM_LABELS_XML);

  console.log(`📁 LWC test workspace: ${workspaceDir}`);
  console.log(`📦 Pre-created components: ${LWC_E2E_COMPONENT_NAMES.join(', ')}`);
  return workspaceDir;
};

/**
 * Minimal SFDX tree for VS Code Web: `sfdx-project.json`, `force-app/main/default/lwc`, and a seeded
 * `labels/CustomLabels.labels-meta.xml` (so the LWC language server can emit `customlabels.d.ts` on startup).
 * LWCs are created in-web via **SFDX: Create Lightning Web Component** so they land in the same FS the Explorer shows.
 */
export const createLwcWebPlaygroundWorkspace = async (): Promise<string> => {
  const workspaceDir = await fs.mkdtemp(path.join(os.tmpdir(), 'vscode-lwc-e2e-'));
  const lwcDir = path.join(workspaceDir, 'force-app', 'main', 'default', 'lwc');
  await fs.mkdir(lwcDir, { recursive: true });
  const labelsDir = path.join(workspaceDir, 'force-app', 'main', 'default', 'labels');
  await fs.mkdir(labelsDir, { recursive: true });
  await fs.writeFile(path.join(labelsDir, 'CustomLabels.labels-meta.xml'), LWC_E2E_SEED_CUSTOM_LABELS_XML);
  const vscodeDir = path.join(workspaceDir, '.vscode');
  await fs.mkdir(vscodeDir, { recursive: true });
  await fs.writeFile(
    path.join(vscodeDir, 'settings.json'),
    JSON.stringify({ 'salesforcedx-vscode-core.push-or-deploy-on-save.enabled': false }, null, 2)
  );
  await fs.writeFile(
    path.join(workspaceDir, 'sfdx-project.json'),
    JSON.stringify(
      {
        packageDirectories: [{ path: 'force-app', default: true }],
        namespace: '',
        sfdcLoginUrl: 'https://login.salesforce.com',
        sourceApiVersion: '64.0',
        defaultLwcLanguage: 'javascript'
      },
      null,
      2
    )
  );
  console.log(`📁 LWC web playground (empty lwc/): ${workspaceDir}`);
  return workspaceDir;
};
