name: Setup E2E
description: Set up Node.js, Wireit caching, and dependencies
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version: ${{ vars.NODE_VERSION || 'lts/*' }}
        cache: npm
    - uses: google/wireit@setup-github-actions-caching/v2
    - name: Install dependencies
      uses: salesforcecli/github-workflows/.github/actions/npmInstallWithRetries@main
