import { LogLevel } from './utilities/constants';
export declare class EnvironmentSettings {
    private static _instance;
    private _vscodeVersion;
    private _specFiles;
    private _devHubAliasName;
    private _devHubUserName;
    private _sfdxAuthUrl;
    private _orgId;
    private _extensionPath;
    private _startTime;
    private _throttleFactor;
    private _javaHome;
    private _useExistingProject;
    private _logLevel;
    private constructor();
    static getInstance(): EnvironmentSettings;
    get vscodeVersion(): string;
    get specFiles(): string[];
    get devHubAliasName(): string;
    get devHubUserName(): string;
    get extensionPath(): string;
    get throttleFactor(): number;
    get startTime(): string;
    get sfdxAuthUrl(): string | undefined;
    get orgId(): string | undefined;
    get javaHome(): string | undefined;
    get useExistingProject(): string | undefined;
    set useExistingProject(existingProject: string | undefined);
    get logLevel(): LogLevel;
}
