import { SpawnOptionsWithoutStdio } from 'child_process';
import { OrgEdition, SfCommandRunResults } from './types';
export type NONE = 'NONE';
export declare function runCliCommand(command: string, ...args: (string | SpawnOptionsWithoutStdio)[]): Promise<SfCommandRunResults>;
export declare function deleteScratchOrg(orgAliasName: string | undefined): Promise<void>;
export declare function orgLoginSfdxUrl(authFilePath: string): Promise<SfCommandRunResults>;
export declare function orgDisplay(usernameOrAlias: string): Promise<SfCommandRunResults>;
export declare function orgList(): Promise<SfCommandRunResults>;
export declare function aliasList(): Promise<SfCommandRunResults>;
export declare function scratchOrgCreate(edition: OrgEdition, definitionFileOrNone: string | NONE, scratchOrgAliasName: string, durationDays: number): Promise<SfCommandRunResults>;
export declare function setAlias(devHubAliasName: string, devHubUserName: string): Promise<SfCommandRunResults>;
export declare function installJestUTToolsForLwc(projectFolder: string | undefined): Promise<void>;
export declare function createUser(systemAdminUserDefPath: string, targetOrg: string | undefined): Promise<SfCommandRunResults>;
export declare function removeEscapedCharacters(result: string): string;
export declare function generateSfProject(name: string, path?: string | undefined, template?: string | undefined): Promise<SfCommandRunResults>;
