# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Develop with Ease with Salesforce Extensions
baseurl: '/tools/vscode' # the subpath of your site, e.g. /blog
url: 'https://developer.salesforce.com' # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

include:
  - _redirects

sass:
  style: compressed

collections:
  articles:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: '' # an empty string here means all files in the project
    values:
      layout: 'default'
  - scope:
      path: ''
      type: articles
    values:
      layout: 'article'
