name: Base E2E Test Suite for Minimum VSCode Version

on:
  workflow_run:
    workflows:
      - Nightly Build Develop
      - Test, Build, and Release
    types:
      - completed

  workflow_dispatch:
    inputs:
      automationBranch:
        description: 'Set the branch to use for automation tests'
        required: false
        default: 'develop'
        type: string
      anInitialSuite:
        description: 'Verify Extensions'
        required: false
        default: true
        type: boolean
      authentication:
        description: 'Authentication'
        required: false
        default: true
        type: boolean
      lwcLSP:
        description: 'LWC LSP'
        required: false
        default: true
        type: boolean
      deployAndRetrieve:
        description: 'Deploy and Retrieve'
        required: false
        default: true
        type: boolean
      apexLsp:
        description: 'Apex LSP'
        required: false
        default: true
        type: boolean
      runApexTests:
        description: 'Run Apex Tests'
        required: false
        default: true
        type: boolean
      vscodeVersion:
        description: 'VSCode Version'
        required: false
        default: '1.82.3'
        type: string
      runId:
        description: 'Run ID of the workflow run that created the vsixes'
        required: true
        type: string
      os:
        description: 'Operating System(s) to run the E2E tests on. Input must be a valid JSON array.'
        required: false
        default: '["ubuntu-latest"]'
        type: string

  workflow_call:
    inputs:
      automationBranch:
        description: 'Set the branch to use for automation tests'
        required: false
        default: 'develop'
        type: string
      anInitialSuite:
        description: 'Verify Extensions'
        required: false
        default: true
        type: boolean
      authentication:
        description: 'Authentication'
        required: false
        default: true
        type: boolean
      lwcLSP:
        description: 'LWC LSP'
        required: false
        default: true
        type: boolean
      deployAndRetrieve:
        description: 'Deploy and Retrieve'
        required: false
        default: true
        type: boolean
      apexLsp:
        description: 'Apex LSP'
        required: false
        default: true
        type: boolean
      runApexTests:
        description: 'Run Apex Tests'
        required: false
        default: true
        type: boolean
      vscodeVersion:
        description: 'VSCode Version'
        required: false
        default: '1.82.3'
        type: string
      runId:
        description: 'Run ID of the workflow run that created the vsixes'
        required: true
        type: string
      os:
        description: 'Operating System(s) to run the E2E tests on. Input must be a valid JSON array.'
        required: false
        default: '["ubuntu-latest"]'
        type: string

jobs:
  anInitialSuite:
    if: ${{ inputs.anInitialSuite || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      testToRun: 'anInitialSuite.e2e.ts'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.82.3' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id  }}
      os: ${{ inputs.os || '["ubuntu-latest"]' }}

  authentication:
    if: ${{ inputs.authentication || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      testToRun: 'authentication.e2e.ts'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.82.3' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id  }}
      os: ${{ inputs.os || '["ubuntu-latest"]' }}

  lwcLSP:
    if: ${{ inputs.lwcLsp || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      testToRun: 'lwcLsp.e2e.ts'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.82.3' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id  }}
      os: ${{ inputs.os || '["ubuntu-latest"]' }}

  deployAndRetrieve:
    if: ${{ inputs.deployAndRetrieve || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      testToRun: 'deployAndRetrieve.e2e.ts'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.82.3' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id  }}
      os: ${{ inputs.os || '["ubuntu-latest"]' }}

  apexLSP:
    if: ${{ inputs.apexLsp || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      testToRun: 'apexLsp.e2e.ts'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.82.3' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id  }}
      os: ${{ inputs.os || '["ubuntu-latest"]' }}

  runApexTests:
    if: ${{ inputs.runApexTests || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      testToRun: 'runApexTests.e2e.ts'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.82.3' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id  }}
      os: ${{ inputs.os || '["ubuntu-latest"]' }}

  slack_success_notification:
    if: ${{ success() }}
    needs:
      [
        anInitialSuite,
        authentication,
        lwcLSP,
        deployAndRetrieve,
        apexLSP,
        runApexTests
      ]
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: 'Base E2E Test Suite'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.82.3' }}
      testsBranch: ${{ inputs.automationBranch || 'develop' }}
      summary: '\n- An Initial Suite: ${{ needs.anInitialSuite.result }}\n- Authentication: ${{ needs.authentication.result }}\n- LWC LSP: ${{ needs.lwcLSP.result }}\n- Deploy and Retrieve: ${{ needs.deployAndRetrieve.result }}\n- Apex LSP: ${{ needs.apexLSP.result }}\n- Run Apex Tests: ${{ needs.runApexTests.result }}'
      result: 'All the tests passed.'
      workflow: 'actions/runs/${{ github.run_id }}'
      type: 'e2e'

  slack_failure_notification:
    if: ${{ failure() }}
    needs:
      [
        anInitialSuite,
        authentication,
        lwcLSP,
        deployAndRetrieve,
        apexLSP,
        runApexTests
      ]
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: 'Base E2E Test Suite'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.82.3' }}
      testsBranch: ${{ inputs.automationBranch || 'develop' }}
      summary: '\n- An Initial Suite: ${{ needs.anInitialSuite.result }}\n- Authentication: ${{ needs.authentication.result }}\n- LWC LSP: ${{ needs.lwcLSP.result }}\n- Deploy and Retrieve: ${{ needs.deployAndRetrieve.result }}\n- Apex LSP: ${{ needs.apexLSP.result }}\n- Run Apex Tests: ${{ needs.runApexTests.result }}'
      result: 'Not all the tests passed.'
      workflow: 'actions/runs/${{ github.run_id }}'
      type: 'e2e'

  slack_cancelled_notification:
    if: ${{ cancelled() }}
    needs:
      [
        anInitialSuite,
        authentication,
        lwcLSP,
        deployAndRetrieve,
        apexLSP,
        runApexTests
      ]
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: 'Base E2E Test Suite'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.82.3' }}
      testsBranch: ${{ inputs.automationBranch || 'develop' }}
      summary: '\n- An Initial Suite: ${{ needs.anInitialSuite.result }}\n- Authentication: ${{ needs.authentication.result }}\n- LWC LSP: ${{ needs.lwcLSP.result }}\n- Deploy and Retrieve: ${{ needs.deployAndRetrieve.result }}\n- Apex LSP: ${{ needs.apexLSP.result }}\n- Run Apex Tests: ${{ needs.runApexTests.result }}'
      result: 'The workflow was cancelled.'
      workflow: 'actions/runs/${{ github.run_id }}'
      type: 'e2e'
