name: Dependabot Auto-Merge

# Uses the battle-tested automerge workflow from salesforcecli/github-workflows
# This automatically merges dependabot PRs that are:
# 1. Up to date with main/develop
# 2. Mergeable (per GitHub)
# 3. All checks have completed and none failed (skipped may not have run)

on:
  # Trigger when checks complete
  check_suite:
    types: [completed]

  # Manual trigger for testing/debugging
  workflow_dispatch:
    inputs:
      skipCI:
        description: 'Skip CI checks and merge immediately'
        required: false
        default: false
        type: boolean

jobs:
  automerge:
    # Only run for dependabot PRs (when checks complete) or manual triggers
    if: github.actor == 'dependabot[bot]' || github.event_name == 'workflow_dispatch'
    uses: salesforcecli/github-workflows/.github/workflows/automerge.yml@main
    secrets: inherit
    with:
      mergeMethod: squash
      skipCI: ${{ github.event.inputs.skipCI || false }}
