name: Dependabot Auto-Merge

# Uses the battle-tested automerge workflow from salesforcecli/github-workflows
# This automatically merges dependabot PRs that are:
# 1. Up to date with main/develop
# 2. Mergeable (per GitHub)
# 3. All checks have completed and none failed (skipped may not have run)

on:
  workflow_dispatch:
  schedule:
    # Run every 3 hours during business hours
    - cron: '0 9,12,15,18 * * 1-5'

jobs:
  automerge:
    uses: salesforcecli/github-workflows/.github/workflows/automerge.yml@main
    secrets: inherit
    with:
      mergeMethod: squash
