name: Dumb action

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Select the release type (default is minor)'
        required: true
        default: 'minor'
        type: choice
        options:
          - minor
          - major
          - patch
          - beta
      version:
        description: version
        type: string
      branch:
        description: branch
        type: string
      result:
        description: Result of the previous workflow
        type: string
jobs:

  slack_notification:
    uses: ./.github/workflows/slack-notification.yml
    with:
      title: "Release Branch v${{ inputs.version }} (${{ inputs.releaseType }})"
      failedEvent: "Create Release Branch"
      successfulEvent: "${{ github.event.repository.html_url }}/tree/${{ inputs.branch }}"
      type: "created"
      result: ${{ inputs.result }}
      workflow: "dumb_action.yml"
