on:
  workflow_call:

jobs:
  linux-integration-tests:
    strategy:
      matrix:
        node_version: [lts/-1, lts/*]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      - run: npm install -g sfdx-cli
      - run: npm install -g junit-merge
      - run: npm ci
      - run: npm run compile
      - run: npm run test:integration-tests-without-system-tests