name: Integration Tests
on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false

jobs:
  windows-integration-tests:
    uses: ./.github/workflows/integrationTestsWindows.yml
    with:
      branch: ${{ inputs.branch }}