name: Nightly Build
on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true

jobs:
  unit-tests:
    uses: ./.github/workflows/unitTests.yml
    with:
      ref: ${{ inputs.branch }}
  integration-tests:
    uses: ./.github/workflows/integrationTests.yml
    with:
      ref: ${{ inputs.branch }}
  build-all:
    uses: ./.github/workflows/buildAll.yml
    with:
      ref: ${{ inputs.branch }}