name: Publish

on:
  workflow_call

jobs: 

  publish-notification: 
    runs-on: 'ubuntu-latest'
    steps: 
      - name: 'Slack Prepublish notification'
        uses: ./.github/workflows/slackNotification.yml
        with:
          title: "Publish waiting for approval in github."
          notification: "Main has been updated."
          type: "notification"
          workflow: "publish.yml"

  publish: 
    runs-on: 'ubuntu-latest'
    environment: publish
    needs: publish-notification
    steps: 
      - name: 'Publish to VSCODE Marketplace'
        run: echo "Not shipped yet!"