name: Publish Types Package to npm (shared)

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      githubTag:
        description: release tag to publish (e.g., v65.2.0)
        required: true
        type: string

jobs:
  publish:
    uses: salesforcecli/github-workflows/.github/workflows/npmPublish.yml@sm/monorepo-npm-publishes
    with:
      githubTag: ${{ github.event.release.tag_name || inputs.githubTag }}
      tag: latest
      packageManager: npm
      nodeVersion: ${{ vars.NODE_VERSION || 'lts/*' }}
      packagePath: ./packages/salesforcedx-vscode-services-types
      dryrun: true
      prerelease: false
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
