name: Release Branch Listener for Generating Change Logs

on:
  push:
    # Only listen for pull requests against release branches
    branches:
      - 'release/v**.**.*' # Push events to branches matching example format refs/heads/release/v17.10.0
    tags-ignore:
      - IgnoreInChangelog # Do not run these steps if the Pull Request has the tag 'IgnoreInChangelog'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [12.4]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm install

      - name: Run Compile
        run: npm run compile

      - name: Build the CHANGELOG
        run: node scripts/change-log-generator.js
