name: Report Installs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  report-installs:
    runs-on: ubuntu-latest
    env:
      VSCE_PERSONAL_ACCESS_TOKEN: ${{ secrets.VSCE_PERSONAL_ACCESS_TOKEN }}
      OVSX_PAT: ${{ secrets.IDEE_OVSX_PAT }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ vars.NODE_VERSION || 'lts/*' }}
          install: 'false'
      - run: pnpm install --frozen-lockfile
      - run: pnpm --version
      - run: node --version
      - run: pnpm report:installs
