name: Slack notification for Create release branch
on:
  workflow_run:
    workflows:
      - Create Release Branch
    types:
      - completed
  workflow_call:
    inputs:
      version:
        description: 'Version'
        required: false
        type: string
      release_type:
        description: 'Release type'
        required: false
        type: string
      branch:
        description: 'Head branch'
        required: false
        type: string

jobs:
  notification_on_success:
    if: success()
    runs-on: ubuntu-latest
    needs: [create_git_tag]
    steps:
      - name: Announce success
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
              "text": "Beta release v${{ env.VERSION }} successfully published",
              "event": "${{ github.event.workflow_run.repository.html_url }}/releases/v${{ env.VERSION }}",
              "repo": "${{ github.event.workflow_run.repository.name }}",
              "result": "${{ github.event.workflow_run.conclusion }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.VSCODE_SLACK_WEBHOOK }}
  notification_on_failure:
    if: failure()
    runs-on: ubuntu-latest
    needs: [create_git_tag]
    steps:
      - name: Announce failure
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
              "text": "Beta release v${{ env.VERSION }} unsuccessfully published",
              "event": "${{ github.event.workflow_run.name }}, run: ${{ github.event.workflow_run.html_url }}",
              "repo": "${{ github.event.workflow_run.repository.name }}",
              "result": "${{ github.event.workflow_run.conclusion }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.IDEE_RELEASE_ALERT_SLACK_WEBHOOK }}