name: Test Slack

on: 
  workflow_dispatch:
  
jobs: 
  slack_notification:
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: "Test: Release Branch v56.7.1 (patch) successfully created"
      failedEvent: "Create Release Branch"
      successfulEvent: "https://github.com/forcedotcom/salesforcedx-vscode/tree/release/v56.7.1"
      type: "created"
      result: "failure"
      workflow: "create-release-branch.yml"
