name: Unit Tests Linux
on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
env:
  NODE_OPTIONS: --max-old-space-size=8192

jobs:
  linux-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION || 'lts/*' }}
          cache: npm
      - uses: google/wireit@setup-github-actions-caching/v2
      - uses: salesforcecli/github-workflows/.github/actions/npmInstallWithRetries@main
      - run: npm run compile
      - run: npm run test
        env:
          WIREIT_PARALLEL: 1

