name: Unit Tests Windows
on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
env:
  NODE_OPTIONS: --max-old-space-size=8192

jobs:
  windows-unit-tests:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ vars.NODE_VERSION || 'lts/*' }}
          install: 'false'
      - uses: google/wireit@setup-github-actions-caching/v2
      - uses: salesforcecli/github-workflows/.github/actions/retry@main
        with:
          command: pnpm install --frozen-lockfile
      - run: pnpm compile
      - run: pnpm test
        env:
          # jest does parallel test execution; too much parallelism actually makes it slower/failure-prone
          WIREIT_PARALLEL: 1
