/*
 * Copyright (c) 2026, salesforce.com, inc.
 * All rights reserved.
 * Licensed under the BSD 3-Clause license.
 * For full license text, see LICENSE.txt file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
import * as fs from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';
import { createHeadlessServer, setupSignalHandlers } from '@salesforce/playwright-vscode-ext';

/**
 * Component names required by the four test specs. Pre-creating them avoids the
 * "SFDX: Create Lightning Web Component" command (which is unreliable in VS Code web
 * because @salesforce/templates writes to memfs, not the virtual workspace FS).
 */
const LWC_TEST_COMPONENTS = ['autoComp', 'gtdHtmlComp', 'gtdJsComp', 'indexComp'];

/** Standard LWC JS content generated by @salesforce/templates (class name is always "Lwc1"). */
const lwcJs = `import { LightningElement } from 'lwc';

export default class Lwc1 extends LightningElement {}
`;

/** Minimal LWC HTML template. */
const lwcHtml = `<template>
</template>
`;

/** LWC metadata file. */
const lwcXml = `<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>64.0</apiVersion>
    <isExposed>false</isExposed>
</LightningComponentBundle>
`;

/**
 * Create a minimal Salesforce DX project workspace for LWC tests.
 * Pre-creates all component files so tests can open them directly via the Explorer
 * without relying on the "SFDX: Create Lightning Web Component" command.
 */
const createLwcTestWorkspace = async (): Promise<string> => {
  const workspaceDir = await fs.mkdtemp(path.join(os.tmpdir(), 'vscode-lwc-e2e-'));
  const lwcDir = path.join(workspaceDir, 'force-app', 'main', 'default', 'lwc');

  await fs.writeFile(
    path.join(workspaceDir, 'sfdx-project.json'),
    JSON.stringify(
      {
        packageDirectories: [{ path: 'force-app', default: true }],
        namespace: '',
        sfdcLoginUrl: 'https://login.salesforce.com',
        sourceApiVersion: '64.0',
        defaultLwcLanguage: 'javascript'
      },
      null,
      2
    )
  );

  // Pre-create each test component
  for (const name of LWC_TEST_COMPONENTS) {
    const compDir = path.join(lwcDir, name);
    await fs.mkdir(compDir, { recursive: true });
    await Promise.all([
      fs.writeFile(path.join(compDir, `${name}.js`), lwcJs),
      fs.writeFile(path.join(compDir, `${name}.html`), lwcHtml),
      fs.writeFile(path.join(compDir, `${name}.js-meta.xml`), lwcXml)
    ]);
  }

  console.log(`📁 LWC test workspace: ${workspaceDir}`);
  console.log(`📦 Pre-created components: ${LWC_TEST_COMPONENTS.join(', ')}`);
  return workspaceDir;
};

if (require.main === module) {
  void createLwcTestWorkspace().then(folderPath => {
    // salesforcedx-vscode-metadata provides the SFDX: Create Lightning Web Component command
    void createHeadlessServer({
      extensionName: 'LWC',
      callerDirname: __dirname,
      additionalExtensionDirs: ['salesforcedx-vscode-metadata'],
      folderPath
    });
    setupSignalHandlers();
  });
}
